FROM dhub.kubesre.xyz/postgres:15-alpine
#FROM dhub.kubesre.xyz/redis:6-alpine
#FROM dockerhub.icu/semitechnologies/weaviate:1.19.0
#FROM dockerhub.icu/langgenius/dify-sandbox:0.2.10
#FROM dockerhub.icu/ubuntu/squid:latest
#FROM dockerhub.icu/langgenius/dify-api:0.15.2
#FROM dockerhub.icu/langgenius/dify-api:0.15.2
#FROM dockerhub.icu/langgenius/dify-web:0.15.2
#FROM dhub.kubesre.xyz/nginx:stable
